language: python
os: linux
env:
  global:
  - SETUP_DIR=$TRAVIS_BUILD_DIR/.

before_install:
- python --version
- pip install -U pip
- pip install flake8
- pip install coverage
- pip install codecov
- pip install pytest
install:
- pip install .[all]
jobs:
  fast_finish: true
  allow_failures:
    - arch: arm64
  include:
  - stage: AMD64
    python: 3.6
    dist: xenial
    after_success:
    - bash <(curl -s https://codecov.io/bash)
  - python: 3.6
    dist: bionic
    if: branch = master
  - python: 3.7
    dist: xenial
    if: branch = master
  - python: 3.7
    dist: bionic
    if: branch = master
  - stage: ARM64
    python: 3.6
    arch: arm64
    dist: xenial
    if: branch = master
  - python: 3.6
    arch: arm64
    dist: bionic
    if: branch = master
  - python: 3.7
    arch: arm64
    dist: xenial
    if: branch = master
  - python: 3.7
    arch: arm64
    dist: bionic
    if: branch = master
  - stage: PyPi
    python: 3.6
    dist: xenial
    if: tag IS present
    before_install:
    - pip install twine
    - pip install --upgrade setuptools wheel
    script:
    - python setup.py sdist bdist_wheel
    - python -m twine upload dist/* -u "${PYPI_USERNAME}" -p "${PYPI_PASSWORD}"
    
script:
- coverage run -m pytest -v tests.py
- coverage xml
- coverage report
- flake8 roboglia --statistics --count
