language: generic

env:
  global:
    # Directory of setup.py
    - SETUP_DIR=$TRAVIS_BUILD_DIR/.

matrix:
  # Don't wait for allowed failures
  fast_finish: true

  include:

    - python: 3.6
      os: linux
      language: python

    - python: 3.6
      os: linux
      arch: arm64
      language: python

before_install:
  - python --version
  - pip install -U pip
  - pip install flake8
  - pip install coverage
  - pip install codecov
  - pip install pytest


install:
  - pip install .[all]

script:
  - coverage run -m pytest -v tests.py
  - flake8 roboglia --statistics --count

after_success:
  - bash <(curl -s https://codecov.io/bash)