language: generic
env:
  global:
  - SETUP_DIR=$TRAVIS_BUILD_DIR/.

before_install:
- python --version
- pip install -U pip
- pip install flake8
- pip install coverage
- pip install codecov
- pip install pytest
install:
- pip install .[all]
jobs:
  fast_finish: true
  include:
  - stage: AMD64
    python: 3.6
    os: linux
    dist: xenial
    language: python
    after_success:
    - bash <(curl -s https://codecov.io/bash)
  - python: 3.6
    os: linux
    dist: bionic
    language: python
    if: branch = master
  - python: 3.7
    os: linux
    dist: xenial
    language: python
    if: branch = master
  - python: 3.7
    os: linux
    dist: bionic
    language: python
    if: branch = master
  - stage: ARM64
    python: 3.6
    os: linux
    arch: arm64
    dist: xenial
    language: python
    if: branch = master
  - python: 3.6
    os: linux
    arch: arm64
    dist: bionic
    language: python
    if: branch = master
  - python: 3.7
    os: linux
    arch: arm64
    dist: xenial
    language: python
    if: branch = master
  - python: 3.7
    os: linux
    arch: arm64
    dist: bionic
    language: python
    if: branch = master
  - stage: Deploy
    python: 3.7
    os: linux
    dist: bionic
    if: tag IS present
    before_install:
    - pip install -U pip
    - pip install twine
    install:
    - pip install .[all]
    script:
    - python -m twine upload dist/* -u "${PYPI_USERNAME}" -p "${PYPI_PASSWORD}"
    
script:
- coverage run -m pytest -v tests.py
- coverage xml
- coverage report
- flake8 roboglia --statistics --count
