language: generic

env:
  global:
    # Directory of setup.py
    - SETUP_DIR=$TRAVIS_BUILD_DIR/.



before_install:
  - python --version
  - pip install -U pip
  - pip install flake8
  - pip install coverage
  - pip install codecov
  - pip install pytest


install:
  - pip install .[all]

jobs:
  # Don't wait for allowed failures
  fast_finish: true

  include:

    - stage: test
      python: 3.7
      os: linux
      language: python
      script:
        - coverage run -m pytest -v tests.py
        - flake8 roboglia --statistics --count
      after_success:
        - bash <(curl -s https://codecov.io/bash)

    - # still test
      python: 3.7
      os: linux
      dist: bionic
      language: python
      script:
        - coverage run -m pytest -v tests.py
        - flake8 roboglia --statistics --count
      after_success:
        - bash <(curl -s https://codecov.io/bash)

    - # still test
      python: 3.7
      os: linux
      arch: arm64
      language: python
      script:
        - coverage run -m pytest -v tests.py
        - flake8 roboglia --statistics --count
      after_success:
        - bash <(curl -s https://codecov.io/bash)

    - stage: deploy
      on:
        tags: true
      python: 3.7
      os: linux
      language: python
      script:
        - echo "here we will deploy to PyPi"
