language: generic

env:
  global:
    # Directory of setup.py
    - SETUP_DIR=$TRAVIS_BUILD_DIR/.

matrix:
  # Don't wait for allowed failures
  fast_finish: true

  include:

    - python: 3.6
      os: linux
      language: python

before_install:
  - python --version
  - pip install -U pip
  - pip install flake8


install:
  - python setup.py install

# script:
#   - python tests/all_tests.py

jobs:
  include:
    - stage: test
      script: python tests/all_tests.py
    - # stage name not required, will continue to use `test`
      script: flake8 roboglia --statistics --count